// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHc8ugZ1hOArAMgQ3jo3cql9x_bORQQWg',
    appId: '1:339094526856:web:d41da46e71d15e07a9383d',
    messagingSenderId: '339094526856',
    projectId: 'ariam-6d0e1',
    authDomain: 'ariam-6d0e1.firebaseapp.com',
    storageBucket: 'ariam-6d0e1.appspot.com',
    measurementId: 'G-ZGEBXDBY03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbCAn7X8GFGy1FlynIDHRI9l9bUSrVvw4',
    appId: '1:339094526856:android:9e58eae0ab53416da9383d',
    messagingSenderId: '339094526856',
    projectId: 'ariam-6d0e1',
    storageBucket: 'ariam-6d0e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_ygj0fxDipNekp6XD9HGbm8BYElJjXxQ',
    appId: '1:339094526856:ios:df021050f5d60baaa9383d',
    messagingSenderId: '339094526856',
    projectId: 'ariam-6d0e1',
    storageBucket: 'ariam-6d0e1.appspot.com',
    iosClientId:
        '339094526856-5mlh97s1eohmqbl4gu2rojp3ira8s85s.apps.googleusercontent.com',
    iosBundleId: 'com.example.ariam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_ygj0fxDipNekp6XD9HGbm8BYElJjXxQ',
    appId: '1:339094526856:ios:df021050f5d60baaa9383d',
    messagingSenderId: '339094526856',
    projectId: 'ariam-6d0e1',
    storageBucket: 'ariam-6d0e1.appspot.com',
    iosClientId:
        '339094526856-5mlh97s1eohmqbl4gu2rojp3ira8s85s.apps.googleusercontent.com',
    iosBundleId: 'com.example.ariam',
  );
}
